services:
  postgres:
    ports: ["5432:5432"]
    restart: unless-stopped

  redis:
    ports: ["6379:6379"]
    restart: unless-stopped

  app-chat-ws:
    # 레지스트리 이미지 대신 로컬 빌드 사용
    build:
      context: ../chat-ws         # ← infra/ 기준 상대경로. base를 첫 번째 -f로 넘기는 전제
      dockerfile: Dockerfile
    # (선택) 빌드 결과에 태그를 붙이고 싶으면 아래 활성화
    # image: chat-ws:dev
    pull_policy: never             # 로컬 빌드만 사용, 원격 pull 금지
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports: ["8080:8080"]
    restart: unless-stopped

  # (선택) chat-history도 로컬 빌드로 쓰려면 아래 주석 해제
  # app-chat-history:
  #   build:
  #     context: ../chat-history
  #     dockerfile: Dockerfile
  #   pull_policy: never
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   ports: ["8081:8081"]
  #   restart: unless-stopped
