services:

  chat-ws:
    build:
      context: ..                # ✅ 루트
      dockerfile: infra/dockerfile/chat-ws.Dockerfile
    pull_policy: never


  chat-history:
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
    build:
      context: ..                # ✅ 루트
      dockerfile: infra/dockerfile/chat-history.Dockerfile
    pull_policy: never


  app-service:
    build:
      context: ..
      dockerfile: infra/dockerfile/app-service.Dockerfile
    pull_policy: never


  app-media:
    build:
      context: ..
      dockerfile: infra/dockerfile/app-media.Dockerfile
    pull_policy: never


  app-auth:
    build:
      context: ..
      dockerfile: infra/dockerfile/app-auth.Dockerfile
    pull_policy: never