apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: chat-app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/localDB
  SPRING_DATASOURCE_USERNAME: localUser
  SPRING_DATASOURCE_PASSWORD: secret
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
